### ISSUE TITLE
SPEED5S-H1MB_F23 with openipc

### ISSUE THREAD

**Issue by ljalves** [guino/ppsapp-rtsp#31]
I have a ppstrong based camera with the hi3518ev300 SoC (board SPEED5S-H1MB_F23) where I have successfully flashed OpenIPC.
No longer on the cloud and I now can stream hls, rtsp, mjpeg, ...
Which SoC does your camera use?

**Comment by guino** [comment]
These are the two I have M7C_AK_V10_1245:

![](https://raw.githubusercontent.com/guino/Merkury720/main/img/boardback.jpg)

and hi3518ev300 BE8S_H1_V10_915:

![](https://raw.githubusercontent.com/guino/BazzDoorbell/master/img/soc.jpg)

There are many other boards listed here: 
https://github.com/guino/ppsapp-rtsp/issues/1 but we don’t have a lot of chip models because most of the patches were made without having to open the devices.

**Comment by ljalves** [comment]
The second one should be able to run OpenIPC (hi3518ev300 soc) - do you know what sensor does it have?

There is a tool to get the hardware info from the camera: https://github.com/OpenIPC/ipctool
Just copy the [binary](https://github.com/OpenIPC/ipctool/releases/download/latest/ipctool) to the sdcard and run it.

**Comment by ljalves** [comment]
Btw, I'm gathering all the info about the hacking done on my camera (a SPEED5S-H1MB_F23 board) [here](https://github.com/ljalves/wiki/blob/patch-1/en/device-chacon-ipcam-ri01.md).

**Comment by guino** [comment]
> Btw, I'm gathering all the info about the hacking done on my camera (a SPEED5S-H1MB_F23 board) [here](https://github.com/ljalves/wiki/blob/patch-1/en/device-chacon-ipcam-ri01.md).

I was hoping it would take longer for other people to publish that uboot password in order to avoid them from changing it in the future but oh well..

I will try to find some time to run that sensor tool in my device - the hardware id “BE8S_H1_V10_915” indicates the board and sensor but I have no full list of possible values and what they actually represent.

**Comment by guino** [comment]
Here's the output for both my devices:
```
/mnt/mmc01 # ./ipctool 
---
chip:
  vendor: SKY39EV2_AK3918E80PIN_MNBD
  model: unknown
ethernet:
  mac: "74:ee:--:--:--:12"
rom:
  - type: nor
    block: 4K
    partitions:
      - name: enc
        size: 0x10000
        sha1: bce80b56
      - name: sys
        size: 0x270000
        sha1: 34476c5d
      - name: app
        size: 0x480000
        sha1: 13051bfa
      - name: cfg
        size: 0xa0000
        path: /home/cfg,jffs2,rw
    size: 7M
ram:
  total: 64M
firmware:
  kernel: "3.4.35 (Mon Dec 7 11:30:43 CST 2020)"
  libc: uClibc 0.9.33.2
  main-app: /mnt/mmc01/ppsapp
```
and:
```
/mnt/mmc01 # ./ipctool 
---
chip:
  vendor: HiSilicon
  model: 3518EV300
  id: 02203c870e0038f1-------------932844f904605c25e3
mdio busy
mdio busy
ethernet:
  mac: "d4:d2:--:--:--:3e"
  u-mdio-phyaddr: 0
  phy-id: 0x00000000
  d-mdio-phyaddr: 0
rom:
  - type: nor
    block: 64K
    partitions:
      - name: enc
        size: 0x10000
        sha1: ef58e856
      - name: sys
        size: 0x310000
        sha1: 96718116
      - name: app
        size: 0x440000
        sha1: 89547352
      - name: cfg
        size: 0x50000
        path: /home/cfg,jffs2,rw
    size: 7M
    addr-mode: 3-byte
ram:
  total: 64M
  media: 27M
firmware:
  kernel: "4.9.37 (Fri Mar 20 21:08:26 PDT 2020)"
  libc: uClibc 0.9.33.2
  sdk: "Hi3516EV200_MPP_V1.0.1.2 B030 Release NoLog (Oct 18 2019, 18:30:38)"
  main-app: /mnt/mmc01/ppsapp
sensors:
- vendor: GalaxyCore
  model: GC2053
  control:
    bus: 0
    type: i2c
    addr: 0x6e
  data:
    type: MIPI
    input-data-type: DATA_TYPE_RAW_10BIT
    lane-id:
    - 0
    - 1
    image: 1920x1080
  clock: 27MHz
```
It is worth mentioning the 2nd one is a doorbell which means 2-way talk and button notifications are a must have (to me anyway).
In the realm of tuya cameras and doorbells these two above are probably the most common hardware out there (along with the ![1080p camera](https://github.com/guino/Merkury1080P) which I do not have).
